### PR TITLE
Fix #202: Display uncaught errors with more detail

### LINKED ISSUE #202: Output stack trace for unhandled errors
Unhandled errors can often be confusing so giving the stack trace will help resolve them

### PR DESCRIPTION
**Pull request by Jameskmonger**
# Description

Display unhandled errors with more detail.

As discussed the stack trace is base64 encoded to prevent any newlines from being messing with the YAML (as a stack trace is very newline heavy)

# Checklist

- [x] I am an awesome developer and proud of my code
- [x] I added / updated / removed relevant unit or integration tests to prove my change works
- [x] I ran all tests using ```npm test``` to make sure everything else still works
- [x] I ran ```npm run review``` to ensure the code adheres to the repository standards

# Additional Information

### CODE REVIEW

File: core/test-output-stream.ts [hunk 1]
```diff
@@ -106,12 +107,40 @@ export class TestOutputStream extends ReadableStream {
...
+           " ---\n" +
+           "   message: \"" + message + "\"\n" +
+           "   severity: fail\n" +
+           "   data:\n" +
+           "     got: " + actual + "\n" +
+           "     expect: " + expected + "\n";
+
+       if (stack) {
+           // encode the stack trace with base64 to prevent new lines from messing with the YAML
+           output = output + "     stack_base64: " + new Buffer(stack).toString("base64") + "\n";
```
Comment (jamesrichford) [inline core/test-output-stream.ts]: looking at YAML spec looks like we should do something like

```
data: |
   There once was a short man from Ealing
   Who got on a bus to Darjeeling
       It said on the door
       "Please don't spit on the floor"
   So he carefully spat on the ceiling
```

i.e. not encoding it and just using the pipe character to show it's a multiline stream (since YAML is supposed to be readable first and it avoids specific implementation of encoding making the tap-bark change simpler)

File: core/test-output-stream.ts [hunk 2]
```diff
@@ -69,11 +69,12 @@ export class TestOutputStream extends ReadableStream {
 
       this._writeOut(`not ok ${testId} ${description}\n`);
 
-      if (error instanceof MatchError === false) {
-         error = new MatchError("the test threw an error", "the test to run", "Test threw " + (<any>error.constructor).name + " with message \"" + error.message + "\"");
+      // if it's a match error then log it properly, otherwise log it as unhandled
+      if (error instanceof MatchError) {
+          this._writeMatchErrorOutput(<MatchError>error);
```
Comment (jamesrichford) [inline core/test-output-stream.ts]: do you need the type guard here, I thought that TypeScript will have an implicit one if it's inside a typed block like the above if statement?

File: core/test-output-stream.ts [hunk 3]
```diff
@@ -106,12 +107,40 @@ export class TestOutputStream extends ReadableStream {
...
+       let sanitisedActual = JSON.stringify(error.actualValue);
+       let sanitisedExpected = JSON.stringify(error.expectedValue);
+
+       this._writeFailure(sanitisedMessage, sanitisedActual, sanitisedExpected);
+
+   }
+
+   private _writeUnhandledErrorOutput(error: Error): void {
+
+       this._writeFailure("The test threw an unhandled error.", "an unhandled error", "no unhandled errors to be thrown", error.stack);
```
Comment (jamesrichford) [inline core/test-output-stream.ts]: I'm not sure this separation is required maybe overcomplicated? as JSON.stringify("string") === "string" and the change you're putting on the message will result in the same output so maybe they call a common function that still sanitises the message, expected and output anyway?

Comment (Jameskmonger) [inline core/test-output-stream.ts]: I think it's good to have a private method for it to keep it as separated as possible. The less logic in each function the better!

File: core/test-output-stream.ts (hunk 1 above)
Comment (Jameskmonger) [inline core/test-output-stream.ts]: As discussed, tap-parser doesn't support multi line strings at the moment.

**Comment by Jameskmonger** [comment]
Here's what it looks like @jamesrichford 

example in tap-bark
